### ISSUE TITLE
POP starting error

### ISSUE THREAD

**Issue by Codefordl** [VeriBlock/nodecore-releases#74] opened 2018-07-30 04:59 UTC
Exception in thread "main" java.lang.IllegalStateException: Expected the service  [FAILED] to be RUNNING, but the service has FAILED
        at com.google.common.util.concurrent.AbstractService.checkCurrentState(AbstractService.java:328)
        at com.google.common.util.concurrent.AbstractService.awaitRunning(AbstractService.java:266)
        at com.google.common.util.concurrent.AbstractIdleService.awaitRunning(AbstractIdleService.java:175)
        at nodecore.miners.pop.d.c.a(DefaultBitcoinService.java:151)
        at nodecore.miners.pop.e.run(DefaultPoPMiner.java:71)
        at nodecore.miners.pop.Program.a(Program.java:66)
        at nodecore.miners.pop.Program.main(Program.java:97)
Caused by: org.bitcoinj.wallet.UnreadableWalletException: Could not connect f8eb5fa973162e7b43b87b2f31be37a80d5c7af638db47f3e5a1b9e6aa889925 to 48c1cb5b4cf29b0b91ea92c6add982b8b4f6325a1ebcffeeca4bf677612a2d08
        at org.bitcoinj.wallet.WalletProtobufSerializer.connectTransactionOutputs(WalletProtobufSerializer.java:703)
        at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:508)
        at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:440)
        at org.bitcoinj.kits.WalletAppKit.loadWallet(WalletAppKit.java:402)
        at org.bitcoinj.kits.WalletAppKit.createOrLoadWallet(WalletAppKit.java:364)
        at org.bitcoinj.kits.WalletAppKit.startUp(WalletAppKit.java:273)
        at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:122)
        at java.lang.Thread.run(Unknown Source)

**Comment by a123b** [comment] 2018-07-30 05:37
Duplicate of #72

**Comment by timstall** [comment] 2019-06-06 21:26
Solved in recent pop miner versions

**Closed by timstall** 2019-06-06 21:26 UTC
Labels: app: PoP Miner, bug
